[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.4",
    "jinja2>=3.1.6",
    "sift-stack-py>=0.4.2",
    "streamlit>=1.43.1",
]
