# render.yaml
services:
  - type: web # Specifies this is a web service
    name: exact-transcriber # Choose a name for your service (same as in Render UI)
    env: python # Specifies the runtime environment
    plan: free # Optional: Specifies the instance type (can be omitted, defaults to free)
    buildCommand: "pip install -r requirements.txt" # Command to install dependencies
    startCommand: "streamlit run main.py --server.port $PORT --server.address 0.0.0.0" # Command to run the Streamlit app
    # Optional: Uncomment and set if you need a specific Python version
    # pythonVersion: "3.11"
    # Optional: Uncomment and set your preferred region
    # region: oregon
