# .streamlit/secrets.toml

# Use GOOGLE_API_KEY as expected by the Google library
GOOGLE_API_KEY = "AIzaSyC3JkxgkLnEiAZQrQ0ZwRO-lh9aVqskpZ0"

# Password for basic app authentication
app_password = "eP3&.'c(JH?`{5RT,[4Q>-"
