# .streamlit/secrets.toml

# Use GOOGLE_API_KEY as expected by the Google library
GOOGLE_API_KEY = "AIzaSyCLo16rK_xA7X9V8S2Ng4BnkvTbv456Fe8"

# Password for basic app authentication
app_password = "eP3&.'c(JH?`{5RT,[4Q>-"
