# .streamlit/secrets.toml

# Use GOOGLE_API_KEY as expected by the Google library
GOOGLE_API_KEY = "AIzaSyBTa9ud3F2yCBheE81NZGffZE7TX8FNKxM"

# Password for basic app authentication
app_password = "eP3&.'c(JH?`{5RT,[4Q>-"
