# .streamlit/secrets.toml

# Use GOOGLE_API_KEY as expected by the Google library
GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY_HERE"

# Password for basic app authentication
app_password = "YOUR_CHOSEN_PASSWORD_HERE"
